sudo: required

language: node_js
node_js:
  - "9"

services:
  - docker

cache:
  directories:
    - "node_modules"

install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - ./build.sh pull
  - ./build.sh install

script:
  - ./build.sh build ${TRAVIS_COMMIT}

after_success:
  - ./build.sh push
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "TODO deploy to test";
    fi
