sudo: required

language: node_js
node_js:
  - "9"

services:
  - docker

cache:
  directories:
    - "node_modules"

install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker pull cshr/lpg-services || true
  - npm install

script:
  - npm run build
  - docker build -t cshr/lpg-services:latest .
    && docker tag cshr/lpg-services:latest cshr/lpg-services:${TRAVIS_COMMIT}
    && docker push cshr/lpg-services
