sudo: required
dist: trusty

language: node_js
node_js:
  - "9"

services:
  - docker

addons:
  chrome: stable

cache:
  directories:
    - environ/lpg-ansible-mvp
    - node_modules
    - pyhome
    - test/webdriver/node_modules

env:
  - ENV_PROFILE=dev

install: true
script: ./environ/ci
