sudo: required

language: node_js
node_js:
  - "9"

services:
  - docker

cache:
  directories:
    - "node_modules"

install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker pull cshr/lpg-services
  - npm install

script:
  - npm run build:all
