sudo: required

language: node_js

services:
  - docker

install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker pull cshr/lpg-ui

script:
  - cd service/ui && npm run sass && npm run build
  - docker build -t cshr/lpg-ui:$TRAVIS_COMMIT -f service/ui/Dockerfile .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push cshr/lpg-ui
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "TODO deploy to test";
    fi
