trigger:
  branches:
    include:
    - master
    - idt-develop
    - idt-feature-LC-*
    - idt-release-v*
    - idt-hotfix-v*
  tags:
    include:
      - '*'

variables:
  - name: acr_repo_suffix
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags') }}:
      value: 'prod'
    ${{ else }}:
      value: 'test'

name: '$(SourceBranchName)-$(Rev:r)'

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.3'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: 'Install'
    inputs:
      command: 'install'

  - task: Npm@1
    displayName: 'Lint'
    inputs:
      command: 'custom'
      customCommand: 'run lint'

  - task: Npm@1
    displayName: 'Build'
    inputs:
      command: 'custom'
      customCommand: 'run build'

  - task: Npm@1
    displayName: 'Test'
    inputs:
      command: 'custom'
      customCommand: 'run test:ts'

  - task: Docker@2
    inputs:
      containerRegistry: 'lpgregistry ACR'
      repository: 'lpg-services/${{ variables.acr_repo_suffix }}'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.SourceBranchName)'
