version: "3.4"
services:
  dgraph-server:
    command: ["dgraph", "server", "--memory_mb", "2048", "--my", "dgraph-server:7080", "--zero", "dgraph-zero:5080"]
    depends_on:
      - dgraph-zero
    image: dgraph/dgraph@sha256:435646c5fc42b7da3879203a6c1d8f246b4181843aed4df6e2afd9cdc11efa30
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
  dgraph-viewer:
    command: ["dgraph-ratel"]
    depends_on:
      - dgraph-server
    image: dgraph/dgraph@sha256:435646c5fc42b7da3879203a6c1d8f246b4181843aed4df6e2afd9cdc11efa30
    ports:
      - 8081:8081
  dgraph-zero:
    command: ["dgraph", "zero", "--my", "dgraph-zero:5080", "--port_offset", "-2000"]
    image: dgraph/dgraph@sha256:435646c5fc42b7da3879203a6c1d8f246b4181843aed4df6e2afd9cdc11efa30
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
  learning-locker-api-server:
    command: ["node", "/opt/learning-locker/api/dist/server"]
    depends_on:
      - mongodb
      - redis
      - mailhog
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    ports:
      - 8082:8082
    working_dir: /opt/learning-locker
  learning-locker-api-worker:
    command: ["node", "/opt/learning-locker/worker/dist/server"]
    depends_on:
      - learning-locker-api-server
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    working_dir: /opt/learning-locker
  learning-locker-ui:
    command: ["node", "/opt/learning-locker/ui/dist/server"]
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    ports:
      - 3000:3000
    depends_on:
      - learning-locker-api-server
    working_dir: /opt/learning-locker
  learning-locker-xapi:
    command: ["node", "/opt/xapi-service/dist/server"]
    depends_on:
      - mongodb
      - redis
      - learning-locker-api-worker
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    ports:
      - 8083:8083
    working_dir: /opt/xapi-service
  mailhog:
    image: mailhog/mailhog@sha256:5be1ae7cf894b58fffbe48f84a0541a3595e53124d460d3fb71b3450a8d11189
    ports:
      - 8025:8025
  mongodb:
    image: mongo@sha256:fbb95eaa5a0c84d0d2098775f166003c568a79f993d91309cee7cda4135bbbfd
  postgres:
    image: cshr/lpg-postgres@sha256:2cca70e22b75afb7fc3d47abb1aa07344700624e2a77d21fed39bac14cc94edc
    ports:
      - 5433:5432
    restart: on-failure
  redis:
    image: redis@sha256:3446883dfe13ab3db67433aace0e72d8cd669c528e60c617c42d6c697f0fa41f
  setup-learning-locker:
    command: ["/opt/learning-locker/./node_modules/.bin/babel-node", "/opt/learning-locker/mkadmin.js"]
    depends_on:
      - mailhog
      - mongodb
    environment:
      - NODE_PATH=/opt/learning-locker
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    working_dir: /opt/learning-locker
  learner-record-service:
    environment:
      XAPI_AUTHORISATION: NjZmMmI0ZmMwMDFlM2RhOTkyZDIzYjU3ZDhhNzQ1NzY1NWJlYTA3ODoxYzBlMWI2ODI3NjA2ZDdlZmVkNzFlMjA0OTM5ZDA0OGY5NGY4NDJi
      XAPI_URL: http://learning-locker-xapi:8083/data/xAPI
    image: cshr/lpg-learner-record:de2ef91757db11500befc33a04701666e7a09599
    links:
      - learning-locker-xapi
    ports:
      - 9000:9000
