version: "3.4"
services:

# ElasticSearch
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana@sha256:0d2565286641d213fdbc26ffe29c33268d31e4820ea7af636ebc7d879d736895
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch@sha256:5b2bb3e91379f04a9da7c477314a24b2428fb1a4c20696991dff54b70d1b4ef3
    ports:
      - 9200:9200
      - 9300:9300
    command: "elasticsearch -E cluster.name=local -E discovery.type=single-node"
# /ElasticSearch

# Learning Locker
  learning-locker-api-server:
    container_name: learning-locker-api-server
    depends_on:
      - mongodb
      - redis
      - mailhog
    image: cshr/lpg-learning-locker-api-server:latest
    ports:
      - 8082:8082

  learning-locker-api-worker:
    container_name: learning-locker-api-worker
    depends_on:
      - learning-locker-api-server
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96

  learning-locker-ui:
    container_name: learning-locker-ui
    image: cshr/lpg-learning-locker-ui:latest
    ports:
      - 3000:3000
    depends_on:
      - learning-locker-api-server

  learning-locker-xapi:
    container_name: learning-locker-xapi
    depends_on:
      - mongodb
      - redis
      - learning-locker-api-worker
    image: cshr/lpg-learning-locker-xapi:latest
    ports:
      - 8083:8083

  mailhog:
    container_name: mailhog-locker-api-worker
    image: mailhog/mailhog@sha256:5be1ae7cf894b58fffbe48f84a0541a3595e53124d460d3fb71b3450a8d11189
    ports:
      - 8025:8025

  mongodb:
    container_name: mongodb
    image: mongo@sha256:fbb95eaa5a0c84d0d2098775f166003c568a79f993d91309cee7cda4135bbbfd

  redis:
    container_name: redis
    image: redis@sha256:3446883dfe13ab3db67433aace0e72d8cd669c528e60c617c42d6c697f0fa41f

  setup-learning-locker:
    command: ["/opt/learning-locker/./node_modules/.bin/babel-node", "/opt/learning-locker/mkadmin.js"]
    depends_on:
      - mailhog
      - mongodb
    environment:
      - NODE_PATH=/opt/learning-locker/setup
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    working_dir: /opt/learning-locker/setup
# /Learning Locker

# CSHR

  learner-record:
    container_name: learner-record
    environment:
      AUTH_USER: user
      AUTH_PASSWORD: password
      XAPI_USERNAME: 66f2b4fc001e3da992d23b57d8a7457655bea078
      XAPI_PASSWORD: 1c0e1b6827606d7efed71e204939d048f94f842b
      XAPI_URL: http://learning-locker-xapi:8083/data/xAPI
    image: cshr/lpg-learner-record:d03993a41fee69e349ca8ad8bf2cd321eab77459
    depends_on:
      - learning-locker-xapi
    ports:
      - 9000:9000

  learning-catalogue:
    container_name: learning-catalogue
    command: ["./wait-for-it.sh", "elasticsearch:9300", "-t", "200", "--", "java", "-jar", "/data/app.jar"]
    depends_on:
      - elasticsearch
    environment:
      AUTH_USER: user
      AUTH_PASSWORD: password
      ELASTICSEARCH_CLUSTER: local
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9300
    image: cshr/lpg-learning-catalogue:80aff817bb275ea692de84f3f6911f537ab19730
    ports:
      - 9001:9001

# /CSHR