version: '3.4'
services:
  # ElasticSearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - 9200:9200
      - 9300:9300
    command: 'elasticsearch -E cluster.name=local -E discovery.type=single-node'
  # /ElasticSearch

  redis:
    image: redis@sha256:3446883dfe13ab3db67433aace0e72d8cd669c528e60c617c42d6c697f0fa41f
    ports:
      - 6379:6379

  # CSHR
  identity:
    container_name: identity
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - APPINSIGHTS_INSTRUMENTATIONKEY=key
      - JWT_KEY=key
    image: lpgregistry.azurecr.io/identity-service/master:latest
    ports:
      - 8080:8080
      - 8081:8081

  learner-record:
    container_name: learner-record
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - OAUTH_SERVICE_URL=http://identity:8080
      - REGISTRY_SERVICE_URL=http://civil-servant-registry:9002
      - LEARNING_CATALOGUE_SERVICE_URL=http://learning-catalogue:9001
      - APPINSIGHTS_INSTRUMENTATIONKEY=key
      - JWT_KEY=key
    image: lpgregistry.azurecr.io/lpg-learner-record/test/master:latest
    depends_on:
      - civil-servant-registry
      - identity
      - learning-catalogue
    ports:
      - 9000:9000

  learning-catalogue:
    container_name: learning-catalogue
    command:
      [
        './wait-for-it.sh',
        'elasticsearch:9300',
        '-t',
        '200',
        '--',
        'java',
        '-jar',
        '/data/app.jar',
      ]
    environment:
      - OAUTH_SERVICE_URL=http://identity:8080
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - REGISTRY_SERVICE_URL=http://civil-servant-registry:9002
      - APPINSIGHTS_INSTRUMENTATIONKEY=key
      - JWT_KEY=key
    image: lpgregistry.azurecr.io/lpg-learning-catalogue/test/master:latest
    depends_on:
      - identity
    ports:
      - 9001:9001

  civil-servant-registry:
    container_name: civil-servant-registry
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - OAUTH_SERVICE_URL=http://identity:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=key
      - JWT_KEY=key
    image: lpgregistry.azurecr.io/civil-servant-registry-service/test/master:latest
    depends_on:
      - identity
    ports:
      - 9002:9002

  report-service:
    container_name: report-service
    environment:
      - OAUTH_SERVICE_URL=http://identity:8080
      - LEARNER_RECORD_URL=http://learner-record:9000
      - REGISTRY_SERVICE_URL=http://civil-servant-registry:9002
      - LEARNING_CATALOGUE_SERVICE_URL=http://learning-catalogue:9001
      - APPINSIGHTS_INSTRUMENTATIONKEY=key
      - JWT_KEY=key
    image: lpgregistry.azurecr.io/lpg-report-service/test/master:latest
    depends_on:
      - identity
      - learner-record
    ports:
      - 9004:9004

  notification-service:
    container_name: notification-service
    environment:
      - OAUTH_SERVICE_URL=http://identity:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=key
      - JWT_KEY=key
    image: lpgregistry.azurecr.io/notification-service/test/master:latest
    depends_on:
      - identity
    ports:
      - 9005:9005
# /CSHR
