#!/bin/bash

end() {
  EXIT_CODE=$1
  MESSAGE="$2"
  echo -e "\n${MESSAGE}"
  exit ${EXIT_CODE}
}

ENV="$1"
TAG="$2"
WEB_HOOK_URL="$3"
UPDATE_TIMEOUT=900

echo "Calling web hook for ${ENV}"
curl --header "Content-Type: application/json" --request POST --data '{}' ${WEB_HOOK_URL}

echo "Checking ${ENV} has been updated to ${TAG}"

START=`date +%s`

while [ $(( `date +%s` - $START )) -lt ${UPDATE_TIMEOUT} ]; do
  version=`curl -s https://${ENV}-lpg.cshr.digital/status | grep "version"`

  if [ -z "${version##*$TAG*}" ]; then
    end 0 "Update complete"
  else
    echo -n "."
    sleep 5;
  fi
done

end 1 "Update timed out"
