#!/bin/bash

end() {
  EXIT_CODE=$1
  MESSAGE="$2"
  echo -e "\n${MESSAGE}"
  exit ${EXIT_CODE}
}

ENV="$1"
TAG="$2"
UPDATE_TIMEOUT=900

echo "Checking ${ENV} has been updated to ${TAG}"


START=`date +%s`

while [ $(( `date +%s` - $START )) -lt ${UPDATE_TIMEOUT} ]; do
  version=`curl https://dev-lpg.cshr.digital/status | grep "version"`

  if [ -z "${version##*$TAG*}" ]; then
    end 0 "update complete"
  else
    echo -n "."
    sleep 5;
  fi
done

end 1 "update timed out"
