export const selectors: Record<string, string> = {
	// counterFraudCourse: 'a[href="/courses/0x390"]',
	bannerConfirmation: '.banner__heading-large',
	courseDuration: 'lpg-course-duration',
	courseInfoTitle: '.heading--page-heading',
	courseLink: '.lpg-course-link',
	courseName: '.lpg-course-name',
	courseTitle: '.learning__title',
	courseType: '.lpg-course-type',
	// fireAwarenessCourse: 'a[href="/courses/0x394"]',
	// firstRequiredBy: '.learning__information-desc:first-child',
	otherSection: '.lpg-other-learning',
	otherSectionCourse: '.lpg-other-learning .lpg-course-name',
	requiredDuration: '.resource__duration',
	requiredProgress: '.resource__status',
	requiredSection: '.lpg-required-learning',
	signoutButton: 'a[href="/sign-out"]',
	suggestedGrid: '.grid-row--suggested',
	suggestedSection: '.lpg-suggestions-section',
	tileAdd: '.lpg-add-tile',
	tileRemove: '.lpg-remove-tile',
	tileTitle: '.lpg-title-tile',
}
